# Generated by Django 4.0.5 on 2022-06-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0004_remove_funcionario_sexo_funcionario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'Estagiário'), ('AS', 'Assistente'), ('JR', 'Júnior'), ('PL', 'Pleno'), ('SR', 'Sênior'), ('GR', 'Gerente')], max_length=2),
        ),
    ]
